# Example docker compose config.

services:
  shairport-sync:
    image: mikebrady/shairport-sync:latest
    network_mode: host
    restart: unless-stopped
    # environment:
    #  S6_KEEP_ENV: 1 # Allow S6 to pass environment variables from compose file
    #  PULSE_SERVER: unix:/tmp/pulseaudio.socket # Path for PulseAudio socket
    #  PULSE_COOKIE: /tmp/pulseaudio.cookie # Path for PulseAudio cookie
    #  XDG_RUNTIME_DIR: /tmp # Path for pipewire
    devices:
      - "/dev/snd" # ALSA device, omit if using PulseAudio
    # volumes:
    #   - ./volumes/shairport-sync/shairport-sync.conf:/etc/shairport-sync.conf #Â Customised Shairport Sync configuration file.
    #   - /run/user/1000/pulse/native:/tmp/pulseaudio.socket # PulseAudio socket when using that backend
    #   - /run/user/1000/pipewire-0:/tmp/pipewire-0 # Pipewire socket when using pipewire
    # command: -o pw # You can specify the desired output with command:
    logging:
      options:
        max-size: "200k"
        max-file: "10"
