name: Configuration (without pa, soundio or apple-alac) for systemd.

on:
  workflow_dispatch:
  push:
    branches: [ "development" ]
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    
jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v4
    - name: Install Dependencies
      run: sudo apt-get -y --no-install-recommends install xmltoman libpopt-dev libconfig-dev libasound2-dev libao-dev libjack-dev libsndio-dev libmosquitto-dev avahi-daemon libavahi-client-dev libsoxr-dev libplist-dev libsodium-dev libavutil-dev libavcodec-dev libavformat-dev  
    - name: Configure
      run: |
        autoreconf -fi
        ./configure --sysconfdir=/etc --with-alsa --with-ao --with-dummy --with-jack --with-pipe --with-sndio --with-stdout --with-soxr --with-avahi --with-ssl=openssl --with-systemd --with-dbus-interface --with-mpris-interface --with-mqtt-client --with-airplay-2
    - name: Make
      run: |
        make -j
    - name: Install
      run: |
        sudo make install
    - name: Invoke
      run: |
        sudo systemctl start shairport-sync
    - name: Terminate
      run: |
        sudo systemctl stop shairport-sync

